### ISSUE TITLE
Assignment 1, Solutions 1, 4 & 6 is not naturally recursive

### ISSUE THREAD

**Issue by cgswords** [letroot/pl-stuff#1]
The solutions to problems one, four, and six uses an internal `define`, and should not. (`define`s are turned into `letrec`s by the compiler, thus violating the rule of not using it.) The naturally recursive solutions are less efficient (they use the stack), but cleaner.

**Comment by letroot** [comment]
Oh okay. I'll check those out.  Thanks.

P.S. Didn't know you were following this :)

**Comment by cgswords** [comment]
By way of example, here's `countdown`:

``` racket
(define countdown
  (lambda (n)
    (cond
      [(zero? n) '(0)]
      [else (cons n (coundown (- n 1)))])))
```

**Comment by letroot** [comment]
Wow!
Gee, my solution feels like a mess.

Okay I think I understand what I should do now.

**Comment by cgswords** [comment]
Every function you write for assignment 1 should be of the form

``` racket
(define name
  (lambda (arguments ...)
    (cond
      [test rhs]
      [test rhs]
      ...
      [else rhs])))
```
